import './globals.css'

import { Rubik } from '@next/font/google'

import type { Metadata } from 'next'

// import { AppContextProvider } from './context/useContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
